### PR TITLE
Update tests to avoid (mostly) network access

### PR DESCRIPTION
**Pull request by desyncr**
`remove` command's test still have network access because local plugins can't be removed from disk.

- Split tests into multiple files grouped by command
- Updated travis-ci configuration

### CODE REVIEW

**Comment by fennecdjay** [comment]
> Split tests into multiple files grouped by command
Very good 😄 .

**Review by fennecdjay — APPROVED** [review]
This seems nice.
I wonder what the .swp files are for?
Fine for me.

**Comment by desyncr** [comment]
`.swp` files are created by default by vim. There is a config to avoid them but it's better to keep them in the `.gitignore`.

**Comment by fennecdjay** [comment]
Thanks for the info. I try to use (neo)vim, but I tend to stick to nano 😕

**Comment by desyncr** [comment]
vim can be journey. I recently restarted my vim configs and I'm currently trying to understand it from the bottom up. These links were quite useful: https://github.com/bpierre/switch-to-vim-for-good#non-optional

**Comment by fennecdjay** [comment]
Nice 🔖.

**Pull request merged**
