### PR TITLE
Disable/remove

### PR DESCRIPTION
**Pull request by fennecdjay**
@zpm-project/zpm-zsh yet has to figure every needed test, but the **C** part migth be ok.

### CODE REVIEW

**Comment by desyncr** [comment]
I think that for `remove` there should be:

- test plugin directory is properly unlinked
- test parent directory is properly removed if necessary (ie, empty)

For `disable`:

- test plugin directory is not removed
- test it can be properly enabled/installed after "disable"

**Comment by fennecdjay** [comment]
Fine. Probably coming soon.

**Comment by fennecdjay** [comment]
Also there is a check that plugin is unlisted.

**Comment by fennecdjay** [comment]
Sorry, I hit a bug: zpm does not print anything if ~/.zpm/.plugin_list is prsent but empty.
Fixing this first.

**Comment by fennecdjay** [comment]
It seems test fails or not depending on zsh version.
Fixing it right now.

**Comment by desyncr** [comment]
It's the same issue with `ls` command's output: https://travis-ci.org/zpm-project/zpm-zsh/jobs/198123860#L180

**Comment by fennecdjay** [comment]
This one is a typo. it should read `'.*/.zpm/plugins/zsh-users/zsh-syntax-highlighting'

**Comment by fennecdjay** [comment]
It seems to work on my station now.
pushing.

**Comment by desyncr** [comment]
Let me take a look at this.

**Comment by desyncr** [comment]
On OS X I got:

    $ zpm "zsh-users/zsh-syntax-highlighting" > /dev/null
    $ zpm remove "zsh-users/zsh-syntax-highlighting" > /dev/null
    $ ls ~/.zpm/plugins/zsh-users/zsh-syntax-highlighting
    -  ls: cannot access '.*/.zpm/plugins/zsh-users/zsh-syntax-highlighting': No such file or directory (re)
    -  [2]
    +  ls: /Users/mini/.zpm/plugins/zsh-users/zsh-syntax-highlighting: No such file or directory
    +  [1]

I solved it with https://gist.github.com/desyncr/f67abee8b1d858aad008bd2dc8273bd7

**Comment by desyncr** [comment]
Another thing I noticed is that (also on OS X) `zpm list` returns a weird character:

     ▲ ~/Playground/zpm-zsh make test
    gcc -Wall -o zpm -g zpm.c
    cram ./zpm.t
    !
    --- zpm.t
    +++ zpm.t.err
    @@ -63,6 +63,7 @@
       [1]
       $ zpm list
       rupa/z .* (re)
    +  \xf0 (esc)

     Can install multiple plugins under the same user.


    # Ran 1 tests, 0 skipped, 1 failed.
    make: *** [test] Error 1

I believe this is a off-by-one error. Should check the implementation a bit further.

**Comment by fennecdjay** [comment]
I'm gonna fix it for travis, maybe we'll handle zsh-version/OSX issues later.

**Comment by fennecdjay** [comment]
It migth be a good thing to test for OSX too.
```
os:
  - linux
  - osx
```

yet install phase migth be different.
However, when can test `TRAVIS_OS_NAME` value to do the appropriate thing.

**Pull request merged**
