### PR TITLE
Save command. At last

### PR DESCRIPTION
**Pull request by fennecdjay**
Still much work left, but it is good to see this here.

rmdir_r() was probably failng do to read-only permission, a simple to chmod() migth be able to fix that, I'll make a PR when ready.

### CODE REVIEW

**Comment by desyncr** [comment]
Wanna try merging master back into `save_command`?

     git checkout save_command
     git fetch --all
     git merge master

You probably will need to update your [remotes](https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes) by pointing to `zpm-project/zpm-zsh` rather than `desyncr/zpm-zsh`, now deprecated.

    git remote rm upstream
    git remote add upstream git@github.com:zpm-project/zpm-zsh.git

Let me know if you have any issues with `git`.

**Comment by fennecdjay** [comment]
> Let me know if you have any issues with git.

Thank you.
I'll probably stick with my fork for origin, but switch upstream remote from desyncr/zpm-zsh to zpm-project/zpm-zsh

**Comment by desyncr** [comment]
If you could perform a [`rebase`](https://git-scm.com/book/en/v2/Git-Branching-Rebasing), even better.

    git checkout save_command
    git fetch upstream
    git rebase upstream/master

**Comment by fennecdjay** [comment]
I'm afraid i get some trouble with `rebase`.
 ...
I'll keep working :-)

**Comment by fennecdjay** [comment]
Can you please close this?
we'll still be able to access the discussion, but I'd like to split it in smaller PRs:

  * save command.
  * remove/uninstall command.
  * fix print_list() return value.

each with corespondiong usage() entry when needed. I'll leave the `README.md` updating up to you.

**Comment by desyncr** [comment]
Alright. I'm gonna close this now.

**Pull request closed without merging**
