### PR TITLE
Add homebrew install instructions

### PR DESCRIPTION
**Pull request by jedahan**
The best we can do for #35 until zpm-zsh is more popular. Hopefully this formula will make it more popular :)

### CODE REVIEW

**Comment by desyncr** [comment]
Looking great! Thanks a lot for the work!

**Review by desyncr — APPROVED** [review]
Looks fine to me!

**Comment by desyncr** [comment]
@fennecdjay Looks good to you? It's a great addition!

**Review by fennecdjay — APPROVED** [review]
Looks good, even thought I'm not a Mac user 😕

**Comment by desyncr** [comment]
@fennecdjay Me neither but I have to deal with it on a daily basis D:

**Comment by jedahan** [comment]
I could write an exherbo exheres, but I haven't tested that in years :)

**Pull request merged**
