### PR TITLE
Improve memory handling.

### PR DESCRIPTION
**Pull request by fennecdjay**
Use heap variable where possible.
Also put some variables at functions top, which is more **C**.

### CODE REVIEW

**Review by desyncr — APPROVED** [review]
Great work!

I better step my ansi c up.

**Comment by fennecdjay** [comment]
I'd love to provide a link.

For my work, I try (and fail) to stick to [this](http://suckless.org/coding_style)

**Comment by desyncr** [comment]
I got "Modern C" by Jens Gustedt to read. Let's see how that goes :P

**Comment by desyncr** [comment]
Thanks for the link btw. Looks good.

**Pull request merged**
