### PR TITLE
Add OS X to travis ci configuration

### LINKED ISSUE #21: Add OS X to Travis CI
Run test suite on OS X.

### PR DESCRIPTION
**Pull request by desyncr**
Fixes #21

### CODE REVIEW

**Comment by desyncr** [comment]
It's failing but that's cool because it's only the tests are not passing on OS X, which we already knew.

**Comment by fennecdjay** [comment]
Looks good.
Can cram handle variables in return values?
I didn't manage to do that.
maybe
```sh
if [ $TRAVIS_OS_NAME = "osx" ]; then sed -i '' 's/\[2\]/[1]/' tests/remove.t; fi
```
would do

**Comment by desyncr** [comment]
@fennecdjay No it does not. We should not adapt tests for each OS. The same behaviour should be displayed regardless of OS.

We should see why return codes won't match on OS X with what's expected to. The root issue is `ls` return code for non-existing directories is `1` (bsd) vs `2` (gnu).
I have changed the check from using `ls` to `[ -d $dir ]`. Which seems to be more reliable.

**Comment by fennecdjay** [comment]
> I have changed the check from using ls to [ -d $dir ]. Which seems to be more reliable.

Nice Idea!

**Comment by fennecdjay** [comment]
> ls return code for non-existing directories is 1 (bsd) vs 2 (gnu).
Nice catch too!

**Comment by fennecdjay** [comment]
> ls return code for non-existing directories is 1 (bsd) vs 2 (gnu).
Nice catch too!

**Comment by desyncr** [comment]
Travis CI's OS X builds are so terrible slow lately. It's painful.

**Comment by desyncr** [comment]
This is something I've seen previously. It seems `zpm` enters on some condition it should not. https://travis-ci.org/zpm-project/zpm-zsh/jobs/199239904#L802

**Comment by desyncr** [comment]
Done!

**Review by fennecdjay — APPROVED** [review]
This is great!
I'm so sorry the malloc fault wazs my bad...
Anyway, it looks good for merging 😸

**Comment by desyncr** [comment]
No need to be sorry that's part of the job :P

**Pull request merged**
