### PR TITLE
Remove/uninstall

### PR DESCRIPTION
**Pull request by fennecdjay**
Also use double-quotes in usage().

### CODE REVIEW

**Review by desyncr — CHANGES_REQUESTED** [review]
We should add tests.

**Comment by fennecdjay** [comment]
Sure thing.

  * test it works if no file
  * test it fails if plugin is not installed
  * test directory is removed
  * test parent directory is removed if empty
  * test /tpm/.zpm.tmp is removed

anything else ?

>  * test it fails if plugin is not installed

we migth need the `plugin_entry_exists()` for that, maybe I should do it first.
what do you think?

**Comment by desyncr** [comment]
> we migth need the plugin_entry_exists() for that, maybe I should do it first.
what do you think?

That would also be useful for https://github.com/zpm-project/zpm-zsh/issues/1. So yes.

**Comment by fennecdjay** [comment]
I'm skipping the `/tmp/.zpm.tmp` test for now, as I don't know how to handle a non readable `/tmp` directory.
Should we move this location (to $PWD, for instance)?

**Comment by desyncr** [comment]
For the time being I'm OK with having /tmp fixed.

**Comment by fennecdjay** [comment]
> For the time being I'm OK with having /tmp fixed.

I'm afraid I'm not sure what this really means.

**Comment by desyncr** [comment]
I meant it's ok as it's now.

DC*
Sent from mobile.

**Comment by fennecdjay** [comment]
We probably need to merge #14 before I go ahead, as it ships `plugin_entry_exists()` and this function is needed or this feature.

**Comment by fennecdjay** [comment]
Its a shame, but I'm still in trouble with rebase...
Could we please close that PR, and I'll do anoher (hopefully cleaner one) based one current HEAD?

------------

but I'll definitely give rebase a closer look ;-)

**Comment by desyncr** [comment]
`git-rebase` can be tricky. Alright I'm closing this.

**Comment by fennecdjay** [comment]
Great. I remember you suggested renaming those commands, yet I can't find the place you did anymore. If you could refresh my memory, it would be nice 😆 .

**Comment by desyncr** [comment]
I thought about using:

- `disable` for `remove`
- `remove` for `uninstall`

[Here](https://github.com/desyncr/zpm-zsh/pull/25#issuecomment-276979223)'s there comment.

What do you think? Make sense?

**Comment by fennecdjay** [comment]
Yes, this is far better.

Thanks for the link. it looks like and can't access desyncr/zpm-zsh issues anymore.

**Comment by desyncr** [comment]
I disabled it so we can leave `desyncr/zpm-zsh` behind. I enabled it again so we can view all previous conversations.

**Comment by fennecdjay** [comment]
😄 
I didn't even know that was possible.

**Comment by desyncr** [comment]
If you go to, say, https://github.com/fennecdjay/Gwion/settings, you'll see the option under "Features". Pretty neat.

**Comment by fennecdjay** [comment]
Thank you.

**Pull request closed without merging**
